EDA:
  folders:
    staging_data_folder: "tft_houses/"
    cleaned_data_folder: "dataframe_model/"
  dataframes:
    df_information_houses: "informations_households.csv"
    df_uk_holidays: "uk_bank_holidays.csv"
    df_weather: "weather_hourly_darksky.csv"

models:    
  train:
    dataframes_folder : "../EDA/dataframe_model/"
  eval_metrics: "eval_metrics/"
  predictions: "predictions/"
  results: "results/"
  parcial: "results/_parcial/"

neural_prophet:
  daily_seasonality: True
  weekly_seasonality: False
  yearly_seasonality: False
  batch_size: 64
  epochs: 100
  accelerator: "gpu"
  learning_rate: 0.001

data:
  time_column: "time"
  target_column: "Energy_kwh"
  covariates:
    - "holiday"
    - "month"
    - "hour"
    - "dayofweek_num"
    - "precipType"
    - "bool_weather_missing_values"